### ISSUE TITLE
VPN names contains non-ascii problem

### ISSUE THREAD

**Issue by jiaoew1991** [ctwise/alfred-workflows#12]
When My VPN name contains Chinese chars the vpn_list.rb throws such exception

```ruby
[ERROR: alfred.workflow.input.scriptfilter] Code 1: vpn_list.rb:7:in `split': invalid byte sequence in US-ASCII (ArgumentError)
	from vpn_list.rb:7:in `block in <main>'
	from vpn_list.rb:6:in `each'
	from vpn_list.rb:6:in `<main>'
```

I change  the 7 line in vpn_list.rb to 

```ruby
	(name, kind) = entry.chomp.encode('UTF-8', :invalid => :replace).split('|')
```
fix the bug.

I am too lazy to submit a pull requests.... So hope you fix it in the next version. 

Thank you for the VPN workflow. It really save a lot of my time!!!

**Comment by ctwise** [comment]
Fix incorporated.
