### ISSUE TITLE
[Menu Bar Search] Separate script filter for showing Services menu items

### ISSUE THREAD

**Issue by Jyqft** [ctwise/alfred-workflows#13]
According to the workflow author, it is possible to show the Services menu items, but it is excluded in order to increase workflow performance.

**So, would it be possible to have a separate script filter for searching through it?** In this way, those who don't need the Services menu items can keep on using the original script filter and ignore the new one, and those who need the Services menu items can access it through Alfred at the cost of speed issues.

**Comment by Jyqft** [comment]
Any word, @ctwise?

**Comment by ctwise** [comment]
It's just too slow. You're welcome to fork and comment out the exception for the services menu.

**Comment by Jyqft** [comment]
Could you please guide me which file and which lines I should look at?

**Comment by ctwise** [comment]
Sure, it's the menudump/UIAccess.m file in the 'menudump' github project. Remove the two lines I've marked in the attached image.
<img width="709" alt="menudump 2016-01-07 09-14-12" src="https://cloud.githubusercontent.com/assets/5510/12172496/34fdf9b8-b51f-11e5-9e36-8994edaf9e6b.png">

**Comment by Jyqft** [comment]
`menudump` doesn't seem to be directory, so I can't access `UIAccess.m`. What do I do?

**Comment by Jyqft** [comment]
Alright. Then what's next? Is it necessary to re-compile `menudump`? Is XCode required?

**Comment by ctwise** [comment]
Yep, you'll have to recompile menudump using XCode. Then copy the binary
into the workflow folder.
