### ISSUE TITLE
[Recent Documents] Workflow has ceased working

### ISSUE THREAD

**Issue by Jyqft** [ctwise/alfred-workflows#17]
Whenever I run it, I get no results (I'm shown my fallback searches). Here's the error log:

    [ERROR: alfred.workflow.input.scriptfilter] Code 1: get_recent_docs.rb:11:in `split': invalid byte sequence in US-ASCII (ArgumentError)
    	from get_recent_docs.rb:11:in `<main>'
    [ERROR: alfred.workflow.input.scriptfilter] Code 1: get_recent_docs.rb:11:in `split': invalid byte sequence in US-ASCII (ArgumentError)
    	from get_recent_docs.rb:11:in `<main>'

**Comment by ctwise** [comment]
Try the latest push please.

**Comment by Jyqft** [comment]
Thank you, it's working just like before again.
