### ISSUE TITLE
license for vpn-toggle ?

### ISSUE THREAD

**Issue by maxandersen** [ctwise/alfred-workflows#18]
Hey,

Any chance you know the origin of your vpn-toggle script or could out a license file in your repo ?

Would like to make sure https://github.com/maxandersen/dk.xam.launchbar which contains a launchbar version of your toggle vpn script has proper license info.

Thanks!

**Comment by ctwise** [comment]
No license to speak of. It's completely public domain. Do whatever you like
with it.

**Comment by maxandersen** [comment]
If that is the case I suggest you add something like a LICENSE MIT file to your project (http://choosealicense.com/licenses/mit/)

As documented at https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license: "the absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. This might not be what you intend."
