### ISSUE TITLE
The search lacks behind the standard one 

### ISSUE THREAD

**Issue by Manuel87** [ctwise/alfred-workflows#23]
Not sure what the probelm actually is, as I’m not a programmer.
I’m just guessing that currently " " (space) is not treated as a AND operator?

<img width="355" alt="screenshot_1" src="https://cloud.githubusercontent.com/assets/6603163/14140407/ae5c7e8c-f670-11e5-8a73-f61de08250a2.png">
<img width="594" alt="screenshot_2" src="https://cloud.githubusercontent.com/assets/6603163/14140411/b35598c4-f670-11e5-8bc9-d97d0de7f302.png">

**Comment by ctwise** [comment]
Spaces work just fine. It doesn't match on tokens, it matches on everything you type. Unfortunately, what displays on the menus doesn't always match what OS/X thinks the menu is displaying. Some applications alter the menu text "on-the-fly" to reflect toggle states or other dynamic events. In those cases, the original menu text is what gets matched, not the dynamic text.
